// Types for the build-time games module generated by the games plugin in vite.config.ts
// (mapped through "paths" in tsconfig).
import type { Game } from './schema.ts'

declare const content: { games: Game[] }
export default content
