// Types for the build-time games modules generated by the games plugin in vite.config.ts
// (mapped through "paths" in tsconfig).
import type { Game, GameSummary } from './schema.ts'

declare const content: { games: GameSummary[] }
export default content
/** Loads one game's full content (step texts, tests and solutions) on demand. */
export function loadGame(id: string): Promise<Game | undefined>
