// Types for the build-time content module generated by the content plugin in vite.config.ts
// (mapped through "paths" in tsconfig).
import type { ContentSet } from './validate.ts'

declare const content: ContentSet
export default content
